### ISSUE TITLE
[A11y 8/25] Accessing badges with screen reader

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-badge#13]
With Voiceover/Chrome: This is largely fine. The order of navigation is a little strange for the badging element by ID portion. I can navigate through the first icon and badge in order, then I reach the go back button and the go forward button, then circle back to their little badges. Not a big deal, but this is the only occurrence where it seems like this order is a little off within the demo. 

On Chrome OS / ChromeVox, similar issue. I'm not able to access those little badges with the screen reader, on the badging element by ID portion on the right though. The left portion is fine. Is this intended?

**Comment by notwaldorf** [comment]
@lpalmaro The badges are elements in the demo.html page, so they get read as separate elements. In the "badging by ID" section I literally defined the elements first, then their badges, which is why we read the elements first, then the badges. I can re-order them to make this less confusing :)

**Comment by lpalmaro** [comment]
SG!
