### ISSUE TITLE
Badge loses position on paper-icon-item select

### ISSUE THREAD

**Issue by Zyzle** [PolymerElements/paper-badge#27]
I have a badge placed on the icon in a `paper-icon-item` whenever this item is selected the badge loses its position.  The issue also occurs if the badge is placed on the text or on the `paper-icon-item` itself

![screenshot from 2015-11-23 17-24-43](https://cloud.githubusercontent.com/assets/3787524/11344226/e1020da2-9207-11e5-96d2-53cfbb75e7bf.png)
![screenshot from 2015-11-23 17-24-50](https://cloud.githubusercontent.com/assets/3787524/11344236/e8660f30-9207-11e5-9aff-2cb4330589f1.png)

I have a plunker replicating the issue here:
http://plnkr.co/edit/dBzseo9VcSBsQBt40EiY?p=preview

**Comment by notwaldorf** [comment]
Blerg, looking. I think it's something with the `::before` styling that `paper-icon-item` is doing.

**Comment by notwaldorf** [comment]
I've sent a PR to fix this in `paper-item`. In the meantime, you can just add this style, which should fix it (see http://jsbin.com/gosogo/edit?html,output):
```css
paper-icon-item {
  position: relative;
}
```

**Comment by Zyzle** [comment]
@notwaldorf awesome, thanks!

**Comment by notwaldorf** [comment]
Fixed!
