### ISSUE TITLE
offsetParent is not set if the element is hidden

### ISSUE THREAD

**Issue by firasdib** [PolymerElements/paper-badge#3]
I want to have a paper badge inside an element that is shown and hidden with the click of a button. When the page loads, it is hidden. The result is that `offsetParent` for the badge is null. You can read about that here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent

This breaks the code resulting in the badge never being positioned after the element has been shown, unless the viewport is being resized which will trigger `_onIronResize` and in turn `_setPosition`.

The only solution I can think of is:
1. Check so offsetParent exists
2. Allow for an event/public function to set the position of the badge.

-- 
Alternatively you scrap your solution all together and just use CSS.
1. The parent must be `position: relative`
2. Set `position: absolute` on badge
3. Set `left: 100%;`
4. Set `top: -(HEIGHT_OF_BADGE/2)px`
This should do the very same thing, just with less problematic code.

Edit: Just read about the `for`-behavior which my solution does not work for.

**Comment by rubenstolk** [comment]
+1, In general, `<paper-badge>` works but throws errors if the parentNode has a dynamic `hidden="[[...]]"` property.

**Comment by rubenstolk** [comment]
@notwaldorf awesome!
