### ISSUE TITLE
Changing default positioning when `for` attribute is unspecified

### ISSUE THREAD

**Issue by traviskaufman** [PolymerElements/paper-badge#31]
@cdata @notwaldorf 

Currently `updatePosition()` is called to position badges in all cases. However, according to the Material Designers, the default positioning of badges (e.g. badges next to text) should be that of superscripted text. I'd like to modify `paper-badge` such that if `for` is not specified, the badge is positioned using css and given `vertical-align: super;`, but wanted to run it by you both first to get some feedback. What are your thoughts on this? Thanks! :smile:

**Comment by notwaldorf** [comment]
Hmm, but that only works if you're assuming the thing you're badging is text, no? Or does `vertical-align: super` work ok for divs? If the latter is true, then go for it!

**Comment by traviskaufman** [comment]
@notwaldorf put together small demo at https://jsfiddle.net/h7rmtydu/1/embedded/result,html,css/

It works as long as the element is not a `block` element. . If the div is given an `inline-block` style (which I assume it would), it works as expected. One edge cases is that if used within a flexbox element it doesn't work. I imagine this is because flexbox takes care of all positioning/alignment. You can get around this, however, by wrapping the badged div within a normal block div, as shown in the demo.

Based on the above information do you think it's cool to change the default styling or should we take another approach?

**Comment by notwaldorf** [comment]
I thiiiiiink that makes sense. Let's go for it, what's the worst that can happen? :)

**Comment by notwaldorf** [comment]
Closing this. We explored this in https://github.com/PolymerElements/paper-badge/pull/35, and it turned out superscripts didn't look the same for icons and badges.

@traviskaufman let me know if that's not the case, and i can re-open this.
