### ISSUE TITLE
paper-badge misplaced on interaction with paper-menu

### ISSUE THREAD

**Issue by Compufreak345** [PolymerElements/paper-badge#32]
Hi,

I tried using paper-badge inside a scrollable paper-menu and as soon as I scroll or click on an item the badge gets misplaced. You can try it here : 

http://jsbin.com/qanapu/edit?html,output

**Comment by Compufreak345** [comment]
FYI : As I used this workaround for issues with polymer components as well, I tried putting a style="position:relative;" in my paper-item - and it worked : 
http://jsbin.com/haxoni/edit?html,output 

Is this intended?

**Comment by notwaldorf** [comment]
I think you have an old version of `paper-item` -- this has already been fixed in the `1.1.3` release.
