### ISSUE TITLE
paper-badge misplaced when hidden on initialisation

### ISSUE THREAD

**Issue by Compufreak345** [PolymerElements/paper-badge#33]
The paper-badge is not placed correctly if it is initialised in a hidden state and later turned visible.

Initially hidden (press "toggle hidden" to change hidden state): 
http://jsbin.com/jemaku/edit?html,console,output

Not initially hidden: 
http://jsbin.com/yikuye/edit?html,output

**Comment by notwaldorf** [comment]
For now, as the docs say, I think a workaround is for you to call `updatePosition` manually. I'm working on doing this automatically, but it probably won't be ready before the holidays
