### ISSUE TITLE
Resizing paper-badge does not resize icon

### ISSUE THREAD

**Issue by acabreros** [PolymerElements/paper-badge#40]
```
<style>
     paper-badge {
         --paper-badge-width: 40px;
         --paper-badge-height: 40px;
     }
</style>
<paper-item id="testForBadge">Test for Badge</paper-item>
<paper-badge for="testForBadge" label="warning" icon="icons:warning"></paper-badge>
```

Setting paper-badge-width and paper-badge-height kept the iron-icon at 12px by 12px when I expected it to scale with the resizing. There doesn't seem to be a mixin to override the iron-icon width and height inside paper-badge either.

**Comment by tstewart15** [comment]
This is a major issue for me as well!!

**Comment by venicia** [comment]
This looks like a simple fix.  Can you expose a style mixin to the iron-icon so we can override the height and width?

**Comment by notwaldorf** [comment]
Would something like [this](https://github.com/PolymerElements/paper-badge/pull/43) work? I.e. automatically resizing the icon rather than adding the mixin

**Comment by eduardosada** [comment]
I have the same problem. I want to set the icon size.

**Comment by targeter21** [comment]
I created https://github.com/PolymerElements/paper-badge/pull/53 to address this. You can now specify the width and height of the icon itself independently from the badge.

**Comment by knyto2** [comment]
Hi, what's the status on this? I see the PR is there and all checks have passed, but it has not been merged due to conflicts.
