### ISSUE TITLE
Wrong label position when using Shadow DOM

### ISSUE THREAD

**Issue by MartinMoizard** [PolymerElements/paper-badge#46]
The label of the paper-badge is not properly centered when shadow DOM is activated:
![paperbadge](https://cloud.githubusercontent.com/assets/395477/15140292/b88d504e-169a-11e6-8d43-b981aa9029ec.png)

**Comment by eduardosada** [comment]
I think this will fix #48 too.

**Comment by notwaldorf** [comment]
Closing, as I can't reproduce this: http://jsbin.com/wuteya/edit?html,output.

Please re-open with a JSBin with reproducible steps.

**Comment by MartinMoizard** [comment]
Hi @notwaldorf : the issue is still reproducible: http://jsbin.com/pepigapawu/edit?html,output

Could you please re-open this issue? Thank you.

**Comment by eduardosada** [comment]
+1

**Comment by FrancoisNeveu** [comment]
+2
