### ISSUE TITLE
Label Within Paper Badge Not Centered

### ISSUE THREAD

**Issue by greenbergjosh** [PolymerElements/paper-badge#50]
### Description
On Chrome, the label within the paper-badge is not centered.  The proper centering occurs on IE.  I believe the issue is that an iron-icon pushes the label.  I can see the iron-icon (12x12) by inspecting the element.  The iron-icon is hidden, but it still takes up space.  This does seem to be related to a similar issue, but it is occurring in the latest version installed from bower.

![image](https://cloud.githubusercontent.com/assets/18703777/15946625/a01dd8b6-2e65-11e6-9d8e-da1009e62b38.png)

![image](https://cloud.githubusercontent.com/assets/18703777/15946652/c0300b60-2e65-11e6-8033-956ee072d069.png)

### Expected outcome

On IE the example appears correctly.

![image](https://cloud.githubusercontent.com/assets/18703777/15946684/e61fe2fa-2e65-11e6-9151-f68f2411d077.png)

### Steps to reproduce

1. polymer init app-drawer-template
2. Drop a paper-badge onto any page
3. Open in chrome

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
I thiiiink this should be fixed in the latest release (that I just release 10 minutes ago). Would you mind double checking that, please?

**Comment by greenbergjosh** [comment]
Yes, it is now working.  That's really excellent.  Thank you.  I am a long-time, non-open-source developer.  This was the first open source bug I ever opened.  You have inspired me to get more involved.  I have found many recent JavaScript technologies to be too flaky and too much like playing a video game (trial-and-error), but I really like the philosophy of Polymer.  I hope it stabilizes and allows acquired skills to be valuable for longer than one year.  Kind Regards.
