### ISSUE TITLE
Badge looses its relative position if you maximize/minimize window from title bar menu in Windows

### ISSUE THREAD

**Issue by devAtPolydeals** [PolymerElements/paper-badge#7]
See the maximized and minimized windows in the attached screenshot. The position of 4 goes haywire when you minimize the window. It goes back to normal when you refresh the window.

![maximize](https://cloud.githubusercontent.com/assets/12582040/9214485/06b20766-4053-11e5-8959-44de82bb76f0.png)

![minimize](https://cloud.githubusercontent.com/assets/12582040/9214486/09197e30-4053-11e5-8883-a2da63f96f0b.png)

HTML is below:
```html
       <!-- Main Toolbar -->
        <paper-toolbar id="mainToolbar">
          <paper-icon-button id="paperToggle" icon="menu" paper-drawer-toggle></paper-icon-button>
		  <span class="title">Polydeals</span>
          <span class="flex"></span>
          <!-- Toolbar icons -->
			<paper-icon-button id="heart" icon="favorite" alt="heart"></paper-icon-button>
			 <paper-badge class="white" for="heart" label="4"></paper-badge> 
          <paper-icon-button icon="search"></paper-icon-button>
        </paper-toolbar>
```

**Comment by notwaldorf** [comment]
Hmm that's a bit weird, since the window resizing should fire an `iron-resize` event. I'll look into it, thanks!

**Comment by notwaldorf** [comment]
I can't reproduce this on MSEdge (on Windows 8), nor on IE10, so I think something was fixed downstream. Please re-open this if it happens again.
